export const enum EnvKey { 
	ENCRYPTION_SACRET_KEY = "ENCRYPTION_SACRET_KEY", 
	MONGO_PATH = "MONGO_PATH",
	API_PORT = "API_PORT",
	JWT_SACRET_KEY = "JWT_SACRET_KEY",
	CLIENT_DOMAIN = "CLIENT_DOMAIN",  
} 